import { Box } from '@mui/material'
import Head from 'next/head'
import BabylonRender from '../src/components/babylon-render'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        sx={{
          '& #bjs-canvas': {
            width: '100%',
            height: '100vh',
            touchAction: 'none',
          },
        }}
      >
        <BabylonRender />
      </Box>
    </>
  )
}
